version: '2.3'
services:
  bootstrap:
    build: geth
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=1234 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./genesis.json:/root/files/genesis.json:ro
      - /etc/localtime:/etc/localtime:ro
      - ./tmp/password:/root/files/password:ro
      - ./tmp/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
      - "30303:30303"
      - "8545:8545"
  eth:
    build: geth
    restart: on-failure
    depends_on:
      - bootstrap
    entrypoint: /root/start.sh
    volumes:
      - ./genesis.json:/root/files/genesis.json:ro
      - /etc/localtime:/etc/localtime:ro
      - ./tmp/password:/root/files/password:ro
      - ./tmp/keystore:/root/.ethereum/devchain/keystore:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=1234 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
    cpus: 1
  netstats:
    build: netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
