version: '2.3'
services:
  eth-node:
    build: geth
    restart: on-failure
    entrypoint: /root/start.sh
    volumes:
      - ./genesis.json:/root/files/genesis.json:ro
      - ./chain/:/root/.ethereum/
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=1234 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
    cpus: 1
    extra_hosts:
      bootstrap: 206.189.48.239
